apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud-app
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend