apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: crud-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: host-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: host-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim